2021-02-08 12:44:06,256 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 13:15:35,053 - django.request - ERROR - Internal Server Error: /photos
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/files.py", line 61, in url
    self._require_file()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'image' attribute has no file associated with it.
2021-02-08 15:31:23,145 - django.request - ERROR - Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py", line 68, in get_context_data
    photo = Photo.objects.get(uu_id=self.kwargs['photo_uu_id'])
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“favicon.ico” is not a valid UUID.']
2021-02-08 15:31:28,662 - django.request - ERROR - Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py", line 68, in get_context_data
    photo = Photo.objects.get(uu_id=self.kwargs['photo_uu_id'])
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“favicon.ico” is not a valid UUID.']
2021-02-08 15:36:57,788 - django.request - ERROR - Internal Server Error: /8
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py", line 68, in get_context_data
    photo = Photo.objects.get(uu_id=self.kwargs['photo_uu_id'])
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“8” is not a valid UUID.']
2021-02-08 15:37:31,320 - django.request - ERROR - Internal Server Error: /8
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py", line 68, in get_context_data
    photo = Photo.objects.get(uu_id=self.kwargs['photo_uu_id'])
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“8” is not a valid UUID.']
2021-02-08 15:37:31,363 - django.request - ERROR - Internal Server Error: /9
Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py", line 68, in get_context_data
    photo = Photo.objects.get(uu_id=self.kwargs['photo_uu_id'])
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/home/jesper/Documents/GitHub/trell-hell/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“9” is not a valid UUID.']
2021-02-08 15:41:41,546 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 15:45:01,965 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py changed, reloading.
2021-02-08 15:45:02,388 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 15:45:08,773 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py changed, reloading.
2021-02-08 15:45:09,321 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 15:53:21,735 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 15:54:09,674 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 15:54:15,150 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:00:41,413 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:03:34,141 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:03:34,486 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:03:40,221 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:04:12,567 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:04:13,054 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:04:17,454 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:04:17,912 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:04:30,247 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:05:02,279 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:05:02,684 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:05:12,169 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:05:12,527 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:05:33,314 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:05:33,684 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:05:39,452 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:06:18,327 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:06:19,345 - nothotdog.settings - INFO -  [x] Processing hOtDoG.
2021-02-08 16:06:19,540 - nothotdog.settings - INFO -  [x] Flagged hOtDoG.
2021-02-08 16:06:19,546 - nothotdog.settings - INFO -  [x] Finished processing hOtDoG.
2021-02-08 16:06:19,546 - nothotdog.settings - INFO -  [x] Probability of hot dog is 0.0 %.
2021-02-08 16:06:52,795 - nothotdog.settings - INFO -  [x] Processing Space.
2021-02-08 16:06:52,893 - nothotdog.settings - INFO -  [x] Flagged Space.
2021-02-08 16:06:52,900 - nothotdog.settings - INFO -  [x] Finished processing Space.
2021-02-08 16:06:52,901 - nothotdog.settings - INFO -  [x] Probability of hot dog is 0.3 %.
2021-02-08 16:07:17,864 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:07:18,238 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:09:23,542 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:09:23,885 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:09:35,533 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/signals/upload_handler.py changed, reloading.
2021-02-08 16:09:35,908 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:09:38,126 - nothotdog.settings - INFO -  [*] Waiting for messages.
2021-02-08 16:09:50,363 - nothotdog.settings - INFO -  [x] Processing Space.
2021-02-08 16:09:50,704 - nothotdog.settings - INFO -  [x] Flagged Space.
2021-02-08 16:09:50,710 - nothotdog.settings - INFO -  [x] Finished processing Space.
2021-02-08 16:09:50,711 - nothotdog.settings - INFO -  [x] Probability of hot dog is 0.0 %.
2021-02-08 16:14:39,507 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py changed, reloading.
2021-02-08 16:14:39,842 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2021-02-08 16:14:43,143 - django.utils.autoreload - INFO - /home/jesper/Documents/GitHub/trell-hell/project2/nothotdog/nothotdog/photos/views.py changed, reloading.
2021-02-08 16:14:43,494 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
